# Generated by Django 3.2 on 2021-05-15 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('First Semester', 'First Semester'), ('First Semester', 'First Semester')], default=('First Semester', 'First Semester'), max_length=30)),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=55)),
                ('course_type', models.CharField(choices=[('Core', 'Core'), ('Elective', 'Elective')], default=('Core', 'Core'), max_length=30)),
                ('course_unit', models.DecimalField(decimal_places=1, max_digits=2)),
                ('minimum_credit', models.PositiveIntegerField(default=1)),
                ('maximum_credit', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.course')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('student', 'student'), ('Course Adviser', 'Course Adviser')], default=('student', 'student'), max_length=20),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Information and Media Studies', 'Information and Media Studies')], default=('Information and Media Studies', 'Information and Media Studies'), max_length=100)),
                ('student_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default=('Full Time', 'Full Time'), max_length=20)),
                ('course_of_study', models.CharField(max_length=100)),
                ('course_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.courseregistration')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
