# Generated by Django 3.2 on 2021-04-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_level',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
