# Generated by Django 3.2 on 2021-05-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210515_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Core Course', 'Core Course'), ('Elective Course', 'Elective Course')], default=('Core Course', 'Core Course'), max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], default=('First Semester', 'First Semester'), max_length=30),
        ),
    ]
