# Generated by Django 3.2 on 2021-05-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210515_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='courses_offered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registration', to='users.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.studentprofile'),
        ),
    ]
