# Generated by Django 3.2 on 2021-05-01 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_studentprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncillorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Mr', 'Mr'), ('Mrs', 'Mrs')], default='Choose Your Title', max_length=10)),
                ('qualification', models.CharField(help_text='What is your qualification?', max_length=100)),
                ('discipline', models.CharField(help_text='What is your area/field of discipline?', max_length=100)),
                ('years_of_exerience', models.CharField(help_text='How many years of academic experience do you have?', max_length=10)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
