# Generated by Django 3.2 on 2021-05-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210515_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='councillorprofile',
            old_name='years_of_exerience',
            new_name='years_of_experience',
        ),
    ]
