# Generated by Django 3.2 on 2021-05-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_years_of_exerience_councillorprofile_years_of_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregistration',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='user',
        ),
    ]
