# Generated by Django 3.2 on 2021-05-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_councillorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(default=True, help_text='Enter your course of study', max_length=100),
            preserve_default=False,
        ),
    ]
