# Generated by Django 3.2 on 2021-05-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210516_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Course Adviser', 'Course Adviser')], default=('Student', 'Student'), max_length=20),
        ),
    ]
