# Generated by Django 3.2 on 2021-05-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councillorprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
